### ISSUE TITLE
Go linter running error, please make sure there's no syntax error, then check for any config error

### ISSUE THREAD

**Issue by maciej-zh** [xxpxxxxp/intellij-plugin-golangci-lint#111]
Constantly popping up: "Go linter running error, please make sure there's no syntax error, then run 'go mod tidy' to make sure deps ok"

I've only installed the plugin - no custom config, running on defaults. Ofc running go mod tidy does not change a thing. Plugin does not work.

**Comment by dingyaguang117** [comment]
+1

**Comment by dingyaguang117** [comment]
It seems golangci-lint can not recognize my package name


bash:

```bash
'/usr/local/bin/golangci-lint' 'run'  '-c' '/Users/ding/workspace/myproject/.golangci.yml' 'pkg/apps/agreementexternal/service/agreementgen/external.go' 
```

got

```
WARN [runner] Can't run linter goanalysis_metalinter: inspect: failed to load package agreementgen: could not load export data: no export data for "git.tigerbrokers.net/ams/customer-report/pkg/apps/agreement/service/agreementgen" 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: inspect: failed to load package agreementgen: could not load export data: no export data for "git.xxxxxx.net/myproject/pkg/apps/agreement/service/agreementgen"
```


the go.mod

```
module git.xxxxxx.net/myproject

go 1.16

...
```

**Comment by dingyaguang117** [comment]
it solved by run `golangci-lint cache clean`

**Comment by maciej-zh** [comment]
`golangci-lint cache clean` does not change a thing.

The error keeps popping up.

**Comment by maciej-zh** [comment]
```
2022-07-07 11:31:32,725 [  36919]   WARN - go-linter - Run error: level=error msg="Running error: context loading failed: no go files to analyze"
. Please make sure the project has no syntax error.
2022-07-07 11:31:32,728 [  36922]   WARN - go-linter - Debug command: cd /Users/maciej/repos/maciej-scratchbook && export PATH=/opt/homebrew/Cellar/go/1.18.1/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin && export GOPATH= && '/opt/homebrew/Cellar/golangci-lint/1.46.2/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '2' '--issues-exit-code' '1' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--no-config' '--disable-all' '-E' 'exportloopref,interfacer,staticcheck,dupl,govet,errorlint,funlen,gocritic,goconst,gocognit,ineffassign,bodyclose,gosec,maligned,unconvert,stylecheck,revive,whitespace,gosimple,goprintffuncname,gocyclo,prealloc' 'my-project/utils/pkg'
2022-07-07 11:31:50,168 [  54362]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Go Linter' id=preference.GoLinterConfigurable
2022-07-07 11:31:51,598 [  55792]   WARN - go-linter - Run error: level=error msg="Running error: context loading failed: no go files to analyze"
. Please make sure the project has no syntax error.
```
Obviously there are no syntax errors, all compiles, tests and works. And there are couple of .go files ;)

**Comment by xxpxxxxp** [comment]
Thanks @maciej-zh ! Can you try run the debug command, that's exactly what the plugin tried under the hood:
```cd /Users/maciej/repos/maciej-scratchbook && export PATH=/opt/homebrew/Cellar/go/1.18.1/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin && export GOPATH= && '/opt/homebrew/Cellar/golangci-lint/1.46.2/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '2' '--issues-exit-code' '1' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--no-config' '--disable-all' '-E' 'exportloopref,interfacer,staticcheck,dupl,govet,errorlint,funlen,gocritic,goconst,gocognit,ineffassign,bodyclose,gosec,maligned,unconvert,stylecheck,revive,whitespace,gosimple,goprintffuncname,gocyclo,prealloc' 'my-project/utils/pkg'```

See if this works well in your terminal.

**Comment by xxpxxxxp** [comment]
Hi @maciej-zh , quote you again in case you missed above message

**Comment by maciej-zh** [comment]
My suspicion is that the plug-in can't deal with project's folder structure like that:
```
./
     somegoproject/
              go.mod
              main.go
     anothergoproject/
              go.mod
              main.go
```
When I accidentally switched to another one with a classic structure of just `go.mod` and `main.go` in the root path it seems to be working fine.
