### ISSUE TITLE
Repeated "Possibly invalid config or syntax error"

### ISSUE THREAD

**Issue by jamesphillpotts-fr** [xxpxxxxp/intellij-plugin-golangci-lint#9]
I get this error in the event log over and over again while in the process of editing/refactoring/etc.

In the application logs, I see this error:

```
2020-03-05 10:52:52,643 [51597316]   WARN -                      go-linter - Run error: level=warning msg="[runner] Can't run linter goanalysis_metalinter: assign: failed prerequisites: inspect@github.com/my/project/pkg/mypkg [github.com/my/project/pkg/mypkg.test]"
level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/path/to/my/project/pkg/mypkg/copied.go:26:9: cannot use &(copiedThing literal) (value of type *copiedThing) as CopiedThing value in return statement: missing method EnsureOrFail /path/to/my/project/pkg/mypkg/copied.go:30:5: 2-valued Read(client, s.destNamespace, s.name, s.key, false) (value of type (string, error)) where single value is expected /path/to/my/project/pkg/mypkg/copied.go:37:5: 2-valued Read(client, s.destNamespace, s.name, s.key, false) (value of type (string, error)) where single value is expected /path/to/my/project/pkg/mypkg/generated.go:22:7: cannot initialize 1 variables with 2 values /path/to/my/project/pkg/mypkg/read.go:14:2: log declared but not used /path/to/my/project/pkg/mypkg/read.go:6:2: \"github.com/sirupsen/logrus\" imported but not used as log]"
level=error msg="Running error: buildssa: analysis skipped: errors in package: [/path/to/my/project/pkg/mypkg/copied.go:26:9: cannot use &(copiedThing literal) (value of type *copiedThing) as CopiedThing value in return statement: missing method EnsureOrFail /path/to/my/project/pkg/mypkg/copied.go:30:5: 2-valued Read(client, s.destNamespace, s.name, s.key, false) (value of type (string, error)) where single value is expected /path/to/my/project/pkg/mypkg/copied.go:37:5: 2-valued Read(client, s.destNamespace, s.name, s.key, false) (value of type (string, error)) where single value is expected /path/to/my/project/pkg/mypkg/generated.go:22:7: cannot initialize 1 variables with 2 values /path/to/my/project/pkg/mypkg/read.go:14:2: log declared but not used /path/to/my/project/pkg/mypkg/read.go:6:2: \"github.com/sirupsen/logrus\" imported but not used as log]"
. Usually it's caused by wrongly configured parameters or corrupted with config file.
```

*Go Linter details*

```
Version: 1.2.2
```

```
$ golangci-lint version
golangci-lint has version 1.23.8 built from 76a82c6 on 2020-03-04T03:53:19Z
```

*Application details*

```
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.22, built on January 14, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-88-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: tabs.alphabetical=true
Non-Bundled Plugins: Karma, Pythonid, com.dmarcotte.handlebars, com.oliverlockwood.plugins.jenkinsfile, org.jetbrains.plugins.go-template, org.jetbrains.plugins.go, com.ypwang.plugin.go-linter, idea.goyacc, intellij.prettierJS, name.kropp.intellij.makefile, net.ashald.envfile, org.intellij.plugins.hcl, org.intellij.scala, org.mule.tooling.intellij.raml, org.toml.lang, ru.adelf.idea.dotenv
```

**Comment by xxpxxxxp** [comment]
Thank you. I've pushed a new build pending JetBrains approval, please check if the new version resolved your issue.

**Comment by xxpxxxxp** [comment]
@jamesphillpotts-fr A new version should be available for upgrade, would you please check if that fixed this issue?

**Comment by jamesphillpotts-fr** [comment]
Thanks @xxpxxxxp, seems to be happier now :+1:

**Comment by tuxslayer** [comment]
Still doesn't work for me. Same error. 
Plugin 1.3.3
golangci-lint version
golangci-lint has version 1.24.0 built from 6fd4383 on 2020-03-15T11:30:52Z


IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
Licensed to Aleksey Yashchenko
You have a perpetual fallback license for this version
Subscription is active until March 2, 2021
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8

**Comment by xxpxxxxp** [comment]
@tuxslayer please open idea log and search for "Debug command: "
then execute the following command in shell, paste any error log here.
You can find idea log in "Help" -> "Show Log"
